name: eternalmodmanager
base: core24
version: '4.1.0'
summary: Mod manager for DOOM Eternal.
description: A cross platform mod manager for DOOM Eternal, making it easier to set-up and install mods in both Windows and Linux.
license: MIT
grade: stable
confinement: strict

package-repositories:
  - type: apt
    ppa: aslatter/ppa

parts:
  rust-deps:
    plugin: nil
    override-build: |
      if ! command -v rustup 2>/dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile=minimal
        export PATH="${HOME}/.cargo/bin:${PATH}"
      fi

  desktop-files:
    plugin: dump
    source: snap/resources/
    organize:
      '*.png': usr/share/icons/hicolor/256x256/apps/
      '*.appdata.xml': usr/share/metainfo/

  eternalmodmanager:
    plugin: rust
    source: .
    after: [rust-deps]
    build-packages:
      - libssl-dev
      - pkg-config
    stage-packages:
      - libadwaita-1-0
      - libgtk-4-1
      - alacritty

apps:
  eternalmodmanager:
    command: bin/eternal_mod_manager
    extensions: [gnome]
    plugs:
      - wayland
      - x11
      - opengl
      - desktop
      - network
      - gsettings

slots:
  eternalmodmanager:
    interface: dbus
    bus: session
    name: io.github.brunoanc.eternalmodmanager
