name: eternalmodmanager
base: core24
version: '4.2.1'
summary: Mod manager for DOOM Eternal.
description: A cross platform mod manager for DOOM Eternal, making it easier to set-up and install mods in both Windows and Linux.
license: MIT
grade: stable
confinement: strict

package-repositories:
  - type: apt
    ppa: aslatter/ppa

parts:
  desktop-files:
    plugin: dump
    source: snap/resources/
    organize:
      '*.png': usr/share/icons/hicolor/256x256/apps/
      '*.appdata.xml': usr/share/metainfo/

  alacritty:
    plugin: nil
    stage-packages:
      - alacritty

  eternalmodmanager:
    plugin: rust
    source: .
    build-packages:
      - libssl-dev

apps:
  eternalmodmanager:
    command: bin/eternal_mod_manager
    extensions: [gnome]
    plugs:
      - wayland
      - x11
      - opengl
      - desktop
      - network
      - gsettings

slots:
  eternalmodmanager:
    interface: dbus
    bus: session
    name: io.github.brunoanc.eternalmodmanager
